config/routes.rb
SampleApp::Application.routes.draw do
  get "microposts/create"

  get "microposts/destroy"

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  root              to: 'static_pages#home'
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  
  <nav>

    <%= render 'layouts/menu' %>
		
  
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contacts", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">Customer</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div id="header_container">
    <span id="logo">
      <%= link_to image_tag("logo2.png", :alt=>"Test application") , root_path %> 
    </span>  
    <span id="headertext">
    	<hgroup>
        	<h1>TEST Application</h1>
      		<h4>The best introduction into Ruby on Rails</h4>
      	</hgroup> 
    </span>  
    <div id="menu">
      
      <nav id="top-menu">
        <%= render 'layouts/menu' %>
		
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_menu.html.erb
<ul class="menu">
  <li class="menuitem"><%= link_to "Home", root_path %></li>
  <li class="menuitem"><%= link_to "Help", help_path %></li>
  <% if signed_in? %>
    <li><%= link_to "Users", users_path %></li>
    <li id="fat-menu" class="dropdown" class="menuitem">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Account <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
        <li class="divider"></li>
        <li>
          <%= link_to "Sign out", signout_path, method: "delete" %>
        </li>
      </ul>
    </li>
  <% else %>
    <li class="menuitem"><%= link_to "Sign in", signin_path %></li>
  <% end %>
</ul>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag    "application", media: "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
			<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
			<%= yield %>
			
			<!--%= debug(params) if Rails.env.development? %-->
		</div>
        <%= render 'layouts/footer' %>  
	</body>
</html>